version: '3'

services:
  sperm-analyzer:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
    restart: always
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app/app.py
    networks:
      - sperm-network

networks:
  sperm-network:
    driver: bridge